name: Build and Deploy
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/checkout@v2
      - run: npm install

      - name: Run Tests
        run: npm test

      - name: Audit and Fix Vulnerabilities
        run: npm audit fix
        continue-on-error: true  

      - name: Exlint
        run: gts lint
        continue-on-error: true

      - name: Build
        run: npm run build
      
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build

      
